### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [Kawameka/Splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by Kawameka** [comment]
Searching around brought me to the "viewport" meta tag. I'm not sure if that's what you meant (honestly, I don't really know what you mean by "responsive effect"), but I included that in hopes that it will solve the problem.

If I'm trying to fix the wrong thing, please let me know!

**Comment by Mikeysax** [comment]
:+1:
